// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onPlantNameChange();
void onLightChange();

String plantName;
float moisture;
CloudLight light;
bool lowWater;
bool pump;

void initProperties(){

  ArduinoCloud.addProperty(plantName, READWRITE, ON_CHANGE, onPlantNameChange);
  ArduinoCloud.addProperty(moisture, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(light, READWRITE, ON_CHANGE, onLightChange);
  ArduinoCloud.addProperty(lowWater, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pump, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
